// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Possumus.Infrastructure.Data;

namespace Possumus.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Possumus.Infrastructure.Data.Entities.Candidato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Candidatos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Apellido = "Giardina",
                            Email = "mgiardina@gmail.com",
                            FechaNacimiento = new DateTime(1982, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Mariano",
                            Telefono = "+5492317517703"
                        },
                        new
                        {
                            Id = 2L,
                            Apellido = "Perez",
                            Email = "juan@gmail.com",
                            FechaNacimiento = new DateTime(1980, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Telefono = "+5492317515544"
                        });
                });

            modelBuilder.Entity("Possumus.Infrastructure.Data.Entities.Empleo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CandidatoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Desde")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Empresa")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Hasta")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("Empleos");
                });

            modelBuilder.Entity("Possumus.Infrastructure.Data.Entities.Empleo", b =>
                {
                    b.HasOne("Possumus.Infrastructure.Data.Entities.Candidato", null)
                        .WithMany("Empleos")
                        .HasForeignKey("CandidatoId");
                });
#pragma warning restore 612, 618
        }
    }
}
